site_name: Arts
site_description: Api for arts
repo_url: https://github.com/MailfTrue/arts
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/MailfTrue">MailfTrue</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Art work: 'api/art-work.md'
theme: material
