# Generated by Django 3.1.7 on 2021-05-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('bas-relief', 'Bas Relief'), ('sculpture', 'Sculpture'), ('picture', 'Picture')], max_length=16)),
                ('show', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Произведение искусства',
                'verbose_name_plural': 'Произведения искусства',
            },
        ),
    ]
